apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: {{PRODUCT_SERVICE_IMAGE}}
        ports:
        - containerPort: 5556
        env:
        - name: PORT
          value: "5556"
        - name: USER_SERVICE_URL
          value: "http://user-service:5555"
        livenessProbe:
          httpGet:
            path: /health
            port: 5556
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5556
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
