apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: {{USER_SERVICE_IMAGE}}
        ports:
        - containerPort: 5555
        env:
        - name: PORT
          value: "5555"
        livenessProbe:
          httpGet:
            path: /health
            port: 5555
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5555
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
